### ISSUE TITLE
zlib.output_compression sous Gandi

### ISSUE THREAD

**Issue by mvdandrieux** [cafecentral/grandcentral#108]
Le flag zlib.output_compression dans le htaccess génère une 500 sur les mutus Gandi...
````
# Pour corriger le bug : https://bugs.php.net/bug.php?id=55544
php_flag zlib.output_compression off
````

**Comment by scux** [comment]
Virons-le.
On avait ajouté ce flag pour corriger une erreur que tu as rencontrés sur un serveur (OVH il me semble).
Moi il ne me sert à rien.

**Comment by mvdandrieux** [comment]
oui mais si on le vire il nique OVH. Je le commente avec une note pour OVH USERS. beb798b
