### ISSUE TITLE
Duplicate content et versions

### ISSUE THREAD

**Issue by mvdandrieux** [cafecentral/grandcentral#127]
Aujourd'hui, le fait d'avoir plusieurs versions miroir permet d'accéder à du contenu par

- domain.name/page
- domain.name/fr/page
- domain.name/en/page

où domain.name/page et domain.name/fr/page sont la même page, ce qui créée des alertes de duplicate content chez google.

A l'époque j'avais résolu le problème en forçant la langue à être toujours présente.
Apple efface la langue par défaut http://www.apple.com et http://www.apple.com/fr puis http://www.apple.com/de...

**Comment by scux** [comment]
@mvdandrieux 

Un canonical ne résoudrait pas simplement le problème ?

**Comment by mvdandrieux** [comment]
@scux bonne idée. Par ailleurs, j'ai vu que cela ne concernait que la home. il suffit de changer
```html
<link rel="canonical" content="<?=URL?>" />
```
par
```html
<link rel="canonical" content="<?=$handledItem['url']?>" />
```

ce que j'ai fait dans le site Grand Central.fr
